### ISSUE TITLE
temporal tcn into future

### ISSUE THREAD

**Issue by drdozer** [philipperemy/keras-tcn#113]
The temporal TCN is set up to fold the "past" values into the "current" summary node. The tree of attention branches is rooted at the most recent data point (the right). Is it possible to flip a switch and get it to root itself at the first data value rather than the last? I'm looking at protein sequences, and they have a well-defined beginning point, but often a rather fuzzy ending.

**Comment by psomers3** [comment]
Can you not just reverse the data you're inputting?

**Comment by drdozer** [comment]
Yes - that's the kludge.

**Comment by psomers3** [comment]
Well, I suppose it could be implemented as another input configuration of the TCN, but I'm of the opinion that it is unnecessary because it wouldn't truly change the functionality of the layer and would just add to the already somewhat large configuration list. But it would be easy to do... @philipperemy thoughts?

@drdozer I have never the term kludge 😄

**Comment by philipperemy** [comment]
Yeah reversing the sequence is best. Most procedures already reverse the sequences anyway for seq2seq.

**Comment by drdozer** [comment]
Thanks - and a related question - we're interested in autoencoder schemes. Is it possible to configure TCN to reverse the attention collapsing, so that in the "decoder" half, it will invert the process of pooling attention?

**Comment by philipperemy** [comment]
@drdozer TCN and LSTM/GRU layers are interchangeable. So whatever works for LSTM/GRU will work for TCN.
