### ISSUE TITLE
Dilations Parameter Advice

### ISSUE THREAD

**Issue by evanharwin** [philipperemy/keras-tcn#223]
Firstly, the documentation in this readme is really good, it's been a great help to me working out the TCN architecture.

I had a quick question on this line:
https://github.com/philipperemy/keras-tcn/blob/81706eaabc069ad27a1786625bbf731b247bf2f0/README.md?plain=1#L129
![image](https://user-images.githubusercontent.com/20156105/150522857-22977b82-31c6-4f5c-9fcc-b7ab41f947ba.png)

When you refer to a 'sequence' length, do you mean looking at the number of timesteps? Or the length of an 'event' in your data?

**Comment by philipperemy** [comment]
@evanharwin thank you very much! A TCN model is more or less a stack of layers containing "a trous" (dilated) convolutions. The `dilations` parameter controls how dilated each convolution is in the network.

If you specify `d=[1,2,4,8]`, 
- you will have 4 layers because `len(d)=4`. 
- `d[0]=1` is your first dilated layer with `dilations=1`. You can read the doc of dilated conv here: https://www.tensorflow.org/api_docs/python/tf/nn/conv1d.
- `d[1]=2` will point to your second dilated layer with `dilations=2`

Dilated convolutions are to keep the number of parameters "low" while increasing how far the network can see in the sequence.

The "trous" or dilated can be seen in white on this visual with the example `d=[1,2,4,8]`:

![image](https://user-images.githubusercontent.com/4516927/150537394-d197568b-7c33-420e-a1b0-54e87bf8d2eb.png)

To find how much dilations, you need you can refer to Table 2 of the original paper: https://arxiv.org/pdf/1803.01271.pdf.

They call it `n` and I think they only use powers of 2.

![image](https://user-images.githubusercontent.com/4516927/150539752-b6714c18-813b-44af-9e62-40cf1be6d925.png)

To answer your question: ideally you want your receptive field to be bigger than the largest of your sequence. Imagine if you have sequences of 20 elements but your receptive field is only 5. That would mean that replacing the first 15 elements with 0 and appending the last 5 values would give you EXACTLY the same result because the TCN will be unable to see further than 5 values in the past.

**Comment by evanharwin** [comment]
Wow thanks for that ♥

That makes a lot of sense. It's a little tricky transferring the understanding from image CNN's, but the exponential dilations are pretty smart.

Do you think it's worth me making a PR like this? or shall I leave it be?

```diff
- `dilations`: It controls how deep your TCN layer is. Usually, consider a list with multiple of 
- two. You can guess how many dilations you need by matching the receptive field (of the TCN) with 
- the sequences' lengths.
+ - `dilations`: It controls how deep your TCN layer is. Usually, consider a list with multiple of
+ two. You can guess how many dilations you need by matching the receptive field (of the TCN) with
+ the length of features in your sequence. For example, if your timeseries is periodic, you might 
+ want to have multiples of that period as dilations.
```


If you think it's good how it is, free to close this issue right away 🙂
