### ISSUE TITLE
Support for Bidirectional Layer

### ISSUE THREAD

**Issue by daniel-v-e** [philipperemy/keras-tcn#225]
Could this TCN implementation hypothetically be modified so that it can be wrapped by `tf.keras.layers.Bidirectional` ?

Currently it is not possible, as layers need the `go_backwards` attribute in order to be wrapped by the bidirectional layer - see https://www.tensorflow.org/api_docs/python/tf/keras/layers/Bidirectional

**Comment by philipperemy** [comment]
@daniel-v-e I don't think it's that hard to implement it.
- We need to add `go_backwards` in the constructor.
- If `go_backwards=True`, we need to flip the time dimension before the TCN layers are called.

**Comment by philipperemy** [comment]
@daniel-v-e I am not sure how hard it is to implement it. I forgot a bit how `Bidirectional` works. Is it concatenating the outputs at each step from two RNNs going forward and backwards? Does it involve "merging" the states (cells) when doing that? Because TCN don't have states compared to GRU or LSTM.

If it's just concatenating outputs at each step where each TCN is independent, then it's def do-able. And it would not be so hard. I guess we can just do:
- We need to add `go_backwards` in the constructor.
- If `go_backwards=True`, we need to flip the time dimension before the TCN layers are called.
- `return_state` could just be an empty list?

**Comment by philipperemy** [comment]
@daniel-v-e Bidirect has been implemented.

You can check it here: https://github.com/philipperemy/keras-tcn/commit/a412190a56dc6ebe67f16d5c63a49ac3d4eb1ba7.

Ref: https://keras.io/examples/nlp/bidirectional_lstm_imdb/

**Comment by philipperemy** [comment]
Pushed in 3.5.0.
